### ISSUE TITLE
Invalid webhook list name causes exception

### ISSUE THREAD

**Issue by brotskydotcom** [brotskydotcom/public-services.py#19]
Found these lines in the running server log:
```log
Jul 29 12:31:11 bdc-public-services app/web.1 Processing webhook items on 'None'...
Jul 29 12:31:11 bdc-public-services app/web.1 Task exception was never retrieved
Jul 29 12:31:11 bdc-public-services app/web.1 future: <Task finished name='Task-393' coro=<transfer_all_webhook_items() done, defined at /app/app/workers/webhook_transfer.py:114> exception=AttributeError("'NoneType' object has no attribute 'split'")>
Jul 29 12:31:11 bdc-public-services app/web.1 Traceback (most recent call last):
Jul 29 12:31:11 bdc-public-services app/web.1   File "/app/app/workers/webhook_transfer.py", line 121, in transfer_all_webhook_items
Jul 29 12:31:11 bdc-public-services app/web.1     retry_list = await process_items(try_list)
Jul 29 12:31:11 bdc-public-services app/web.1   File "/app/app/workers/webhook_transfer.py", line 45, in process_items
Jul 29 12:31:11 bdc-public-services app/web.1     environ, guid, retry_count = list_key.split(":")
Jul 29 12:31:11 bdc-public-services app/web.1 AttributeError: 'NoneType' object has no attribute 'split'
```
Clearly the fact that `None` was used as a key in a processing list is also a bug.  But we shouldn't crash because of it.  That's this bug.

**Comment by brotskydotcom** [comment]
This is actually a symptom of #22.  Closing this one as a dup.
